/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HeroRecipeCard: typeof import('./src/components/home/hero-recipe-card.vue')['default']
    HomeHeader: typeof import('./src/components/home/home-header.vue')['default']
    HomeTabBar: typeof import('./src/components/home/home-tab-bar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutTag: typeof import('nutui-uniapp/components/tag/tag.vue')['default']
    SectionBlock: typeof import('./src/components/home/section-block.vue')['default']
  }
}
